name: Docker Playwright


on:
    push:
        branches: [main, develop, docker]
    pull_request:
        branches: [main]
jobs:
    # Run tests inside Docker container
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build Docker image
              run: docker build -t playwright-tests .

            - name: Run tests in Docker container
              run: |
                  docker run --rm \
                  -e TEST_USER_EMAIL='standard_user' \
                  -e TEST_USER_PASSWORD='secret_sauce' \
                  -e HEADLESS='true' \
                  playwright-tests \
                  pytest tests/smoke/ -n auto
